replicaCount: 2

image:
  repository: azurecicdpoc.azurecr.io/azurecicdpoc
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080   # optional, you can specify or let Kubernetes assign
containerPort: 3000
